### PR TITLE
update readme to output texpreview as html

### PR DESCRIPTION
**Pull request by yonicd**
add tex_opts command in readme to enable html outputs for readme

### CODE REVIEW

**Comment by malcolmbarrett** [comment]
Thanks, @yonicd! While I've got you here, is there an easy way to avoid making the images so blown up in the HTML output? In the LaTeX version, they would be considerably smaller. 

e.g. the PDF version of the README looks like this


Any thoughts?

**Comment by yonicd** [comment]
there are html dim opts in the tex_opts that should be able to control that

```r
> texPreview::tex_opts$get('opts.html')
$width
[1] "100%"

$height
[1] "100%"
```

in general there are a lot of options to control the output. many of them are there to help control how the image comes out in the internal viewer. 

a good one to know for controlling the size of the image in a pdf is the boolean resizebox, which wraps `resizebox{}` around the tex.

```r
> texPreview::tex_opts$get()

$fileDir
NULL

$margin
$margin$left
[1] 10

$margin$top
[1] 5

$margin$right
[1] 10

$margin$bottom
[1] 5


$imgFormat
[1] "png"

$print.xtable.opts
list()

$opts.html
$opts.html$width
[1] "100%"

$opts.html$height
[1] "100%"


$cleanup
[1] "aux" "log" "Doc"

$engine
[1] "pdflatex"

$returnType
[1] "viewer"

$density
[1] 150

$resizebox
[1] TRUE

$svg_max
[1] 80000
```

**Comment by yonicd** [comment]
my mistake. the returnType html basically ports the process to magick, with the idea being that knit chunks can control the output dim.

you can also control the image size in practice directly with magick

```r
> dagtex() %>% 
+   add_node("x") %>% 
+   add_node("y") %>% 
+   add_edge("x", "y", is_curved = TRUE) %>% 
+   plot()%>%magick::image_resize('100x')
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
# A tibble: 1 x 7
  format width height colorspace matte filesize density
  <chr>  <int>  <int> <chr>      <lgl>    <int> <chr>  
1 PNG      100     33 Gray       FALSE        0 320x320
```

**Comment by yonicd** [comment]
it was simpler than what i thought. you set the out.width in the global chunk to be 100% which warped all the image outputs. setting it to 25% got the images to look normal again.

**Comment by malcolmbarrett** [comment]
Hmm that does seem to be the best option. I'd like it if output was a little more predictable, but there doesn't seem to be a good way about it. Having dug a bit through the source code for both texPreview and magick, there isn't an obvious way to work around it, and `image_resize()/scale()` don't look great on my end. 

Anyway, thanks again!

**Comment by yonicd** [comment]
if you want to try i added a [branch](https://github.com/metrumresearchgroup/texPreview/tree/html_resize) where you can control the image resize within texpreview as part of the call the branch is html_resize, and you use it as all the other options (either in tex_preview(...,html_resize='50%') or in tex_opts$set(html_resize = '50%') globally)

**Comment by malcolmbarrett** [comment]
that's a good addition, but for some reason using `image_resize()` looks quite bad on my end (pretty blurry)

**Comment by yonicd** [comment]
that's because the html width is 100% and screws with the dpi of the image, dont set it for the whole doc, but by chunk to get better control

**Comment by malcolmbarrett** [comment]
even removing the global chunk option or using `image_resize()` in an interactive session, it ends up blurry, whereas setting out.width does not

**Comment by yonicd** [comment]
Huh...ok... don’t think i can change anything in texPreview since it just returns an magick object for rmd to render

**Pull request merged**
